pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["alterar_lote_grade.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; Alterar Lote/Grade","Alteração de lote no terminal de Venda/Compra Clicar com botão direito do mouse para selecionar a opção &#8220; Alterar Lote/Grade&#8221;  No terminal de...",""],
["aredotamento.html","Faq &#62; FAQ &#62; Arredondamento/Truncamento nos ECFs Bematech","Arredondamento/Truncamento nos ECFs Bematech   Caro Partner e Desenvolvedor Bematech,  Nesta edição de nosso Bematech Flash Tip, va...",""],
["aredotamento2.html","Faq &#62; FAQ &#62; Os modelos de impressoras fiscais térmicas Bematech","Os modelos de impressoras fiscais térmicas Bematech (MP-2100 TH FI, MP-3000 TH FI, MP-4000 TH FI e MP-7000 Th FI), possuem interface USB para comu...",""],
["aredotamento2_2.html","Faq &#62; Os modelos de impressoras fiscais térmicas Bematech 2","Os modelos de impressoras fiscais térmicas Bematech (MP-2100 TH FI, MP-3000 TH FI, MP-4000 TH FI e MP-7000 Th FI), possuem interface USB para comu...",""],
["aredotamento3.html","Faq &#62; FAQ &#62; OS ONZE MANDAMENTOS BOM USUÁRIO DE ECF","ASSUNTO: OS ONZE MANDAMENTOS BOM USUÁRIO DE ECF. EMISSOR DE CUPOM FISCAL I Não utilizar, principalmente na área de atendimento ao público, quaisqu...",""],
["aredotamento3_2.html","Faq &#62; OS ONZE MANDAMENTOS BOM USUÁRIO DE ECF 2","ASSUNTO: OS ONZE MANDAMENTOS BOM USUÁRIO DE ECF. EMISSOR DE CUPOM FISCAL I Não utilizar, principalmente na área de atendimento ao público, quaisqu...",""],
["aredotamento4.html","Faq &#62; FAQ &#62; Aredotamento","Roteiro para configuração de ECF Parametrizar Estação: ECF Identificar Modelo de ECF Informar Porta &#60; Se deixar em branco ira utilizar a porta ...",""],
["aredotamento4_2.html","Faq &#62; Aredotamento 2","Roteiro para configuração de ECF Parametrizar Estação: ECF Identificar Modelo de ECF Informar Porta &#60; Se deixar em branco ira utilizar a porta ...",""],
["aredotamento_2.html","Faq &#62; Arredondamento/Truncamento nos ECFs Bematech 2","Arredondamento/Truncamento nos ECFs Bematech   Caro Partner e Desenvolvedor Bematech,  Nesta edição de nosso Bematech Flash Tip, va...",""],
["atualizacao_da_biblioteca.html","Faq &#62; Faq DLL &#62; Atualização da Biblioteca","Em caso de atualização da biblioteca, quando se tratar de uma mesma versão (considerar a parte numérica, ex. 1.4), não será necessário fazer o reg...",""],
["atualizandostatushcegestor.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Rotinas de Manutenção &#62; Atualizando Status HC e Gestor","Para Atualizar o status de uma NFe no Banco do High-Commerce ou no Gestor ",""],
["atualizarnf-e.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Procedimentos Instalação NF-e 2G 2 &#62; Instalação NFe &#62; Estrutura e Pastas &#62; Atualizar NFe 1.0 para 2.0","2.1 – Desabilitar o Serviço do Firebird; 2.2 – Realizar uma copia da pasta Conttroller\\Notaeletronica; 2.3 – Renomear a pasta copiada para &#8220;NotaEl...",""],
["backup___restore.html","Guia de Orientações e Treinamentos  &#62; Módulo Diversos &#62; Backup / Restore","Backup Database O IBExpert Serviços de menu item de backup de banco de dados permite que você crie um backup ou cópia do banco de d...",""],
["bametech_usb.html","Bamatech USB","Instalando o driver USB • Após o download do pacote de dlls e drivers, você precisa descompactar • Certifique-se de o usuário logado tem permissõe...",""],
["bametech_usb_2.html","Bamatech USB","Instalando o driver USB • Após o download do pacote de dlls e drivers, você precisa descompactar • Certifique-se de o usuário logado tem permissõe...",""],
["barrasdeferramentas.html","Guia de Orientações e Treinamentos  &#62; Instalação e Abertura do HC  &#62; IBExpert &#62; Barras de Ferramentas","Barra de ferramentas de banco de dados Esta barra de ferramentas padrão pode ser visto na principal IBExpert janela. Ele pode ser m...",""],
["cadastro.html","Guia de Orientações e Treinamentos  &#62; Visão Geral &#62; Cadastros","É a primeira opção do menu principal e dá acesso às Tabelas e aos Cadastros existentes no sistema.",""],
["cadastros.html","Guia de Orientações e Treinamentos  &#62; Módulo Impostos &#62; Sped 2 &#62; Visita 1 &#62; Cadastros","É a primeira opção do menu principal e dá acesso aos Cadastros existentes no sistema.",""],
["cadastros_de_clientes_fornecedores.html","Guia de Orientações e Treinamentos  &#62; Visão Geral &#62; Cadastros &#62; Cadastros de Clientes/Fornecedores","Este é um dos mais importantes cadastros disponíveis a todos os sistemas que compõem as soluções integradas High-Commerce. Neste capítulo descreve...",""],
["cadastros_de_moedas2.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; Instalação ECF &#62; Cadastros de Moedas","Cadastros de Moedas    ( Nome da moeda deve está como foi registrada na ECF)      Cadastros de Moedas ECF    At...",""],
["cadastros_de_moedas2_2.html","Guia de Orientações e Treinamentos  &#62; Módulo Relatórios &#62; Visão Geral de todos os Cadastros_2 &#62; Cadastros de Moedas_2","Cadastros de Moedas    ( Nome da moeda deve está como foi registrada na ECF)      Cadastros de Moedas ECF    At...",""],
["cadastros_de_moedas2_3.html","Guia de Orientações e Treinamentos  &#62; Módulo Bancario &#62; Visão Geral de todos os Cadastros_3 &#62; Cadastros de Moedas_3","Cadastros de Moedas    ( Nome da moeda deve está como foi registrada na ECF)      Cadastros de Moedas ECF    At...",""],
["cadastros_de_servicos.html","Guia de Orientações e Treinamentos  &#62; Visão Geral &#62; Cadastros &#62; Cadastros de Serviços","Enter topic text here.",""],
["cadastros_de_vendedores.html","Guia de Orientações e Treinamentos  &#62; Visão Geral &#62; Cadastros &#62; Cadastros de Vendedores","Enter topic text here.",""],
["cadastros_gerais.html","Guia de Orientações e Treinamentos  &#62; Visão Geral &#62; Cadastros &#62; Cadastros Gerais","Chamamos de tabelas gerais aquelas que contém informações complementares que são por vários módulos do sistema.",""],
["cadastros_itens.html","Guia de Orientações e Treinamentos  &#62; Visão Geral &#62; Cadastros &#62; Cadastros Itens","Enter topic text here.",""],
["cadastros_modelos.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; Instalação ECF &#62; Cadastros Modelos","Cadastros Modelos    Os modelos devem ser configurados de acordo com suas receptivas Espécies:   Cupom Fiscal= CF Nota Única = NF N...",""],
["cadastros_modelos_2.html","Guia de Orientações e Treinamentos  &#62; Módulo Relatórios &#62; Visão Geral de todos os Cadastros_2 &#62; Cadastros Modelos_2","Cadastros Modelos    Os modelos devem ser configurados de acordo com suas receptivas Espécies:   Cupom Fiscal= CF Nota Única = NF N...",""],
["cadastros_modelos_3.html","Guia de Orientações e Treinamentos  &#62; Módulo Bancario &#62; Visão Geral de todos os Cadastros_3 &#62; Cadastros Modelos_3","Cadastros Modelos    Os modelos devem ser configurados de acordo com suas receptivas Espécies:   Cupom Fiscal= CF Nota Única = NF N...",""],
["cadastro_cliente.html","Guia de Orientações e Treinamentos  &#62; Módulo Cadastros &#62; Visão Geral de todos os Cadastros &#62; Cadastro de Clientes/Fornecedor &#62; Cadastro Cliente","Este é um dos mais importantes cadastros disponíveis a todos os sistemas que compõem as soluções integradas. Neste capítulo descrevemos as funções...",""],
["cadastro_cliente_2.html","Guia de Orientações e Treinamentos  &#62; Módulo Relatórios &#62; Visão Geral de todos os Cadastros_2 &#62; Cadastro de Clientes/Fornecedor_2 &#62; Cadastro Cliente_2","Este é um dos mais importantes cadastros disponíveis a todos os sistemas que compõem as soluções integradas. Neste capítulo descrevemos as funções...",""],
["cadastro_cliente_3.html","Guia de Orientações e Treinamentos  &#62; Módulo Bancario &#62; Visão Geral de todos os Cadastros_3 &#62; Cadastro de Clientes/Fornecedor_3 &#62; Cadastro Cliente_3","Este é um dos mais importantes cadastros disponíveis a todos os sistemas que compõem as soluções integradas. Neste capítulo descrevemos as funções...",""],
["cadastro_de_clientes_fornecedo.html","Guia de Orientações e Treinamentos  &#62; Módulo Cadastros &#62; Visão Geral de todos os Cadastros &#62; Cadastro de Clientes/Fornecedor","Campos Obrigatórios  Pessoa = Jurídica Nome = Razão social do cliente, evitar caracteres acentuado e &#38;  Dados Principais:(Fig 1) &#38;nb...",""],
["cadastro_de_clientes_fornecedo_2.html","Guia de Orientações e Treinamentos  &#62; Módulo Relatórios &#62; Visão Geral de todos os Cadastros_2 &#62; Cadastro de Clientes/Fornecedor_2","Campos Obrigatórios  Pessoa = Jurídica Nome = Razão social do cliente, evitar caracteres acentuado e &#38;  Dados Principais:(Fig 1) &#38;nb...",""],
["cadastro_de_clientes_fornecedo_3.html","Guia de Orientações e Treinamentos  &#62; Módulo Bancario &#62; Visão Geral de todos os Cadastros_3 &#62; Cadastro de Clientes/Fornecedor_3","Campos Obrigatórios  Pessoa = Jurídica Nome = Razão social do cliente, evitar caracteres acentuado e &#38;  Dados Principais:(Fig 1) &#38;nb...",""],
["cadastro_de_empresas.html","Guia de Orientações e Treinamentos  &#62; Configurações Básicas  &#62; Cadastro de Empresas","/* */ Guia de Orientações e Treinamentos Configurações Básicas Cadastro de Empresas Navigation: Guia de Orientações e Treinamentos Configurações B...",""],
["cadastro_de_produtos.html","Guia de Orientações e Treinamentos  &#62; Módulo Cadastros &#62; Visão Geral de todos os Cadastros &#62; Cadastro de Produtos","Identificação do Item  Código do Produto = 60 caracteres máximo Nome = 120 caracteres máximo Tipo = definir conforme;  -Produtos = Todos...",""],
["cadastro_de_produtos_2.html","Guia de Orientações e Treinamentos  &#62; Módulo Relatórios &#62; Visão Geral de todos os Cadastros_2 &#62; Cadastro de Produtos_2","Identificação do Item  Código do Produto = 60 caracteres máximo Nome = 120 caracteres máximo Tipo = definir conforme;  -Produtos = Todos...",""],
["cadastro_de_produtos_3.html","Guia de Orientações e Treinamentos  &#62; Módulo Bancario &#62; Visão Geral de todos os Cadastros_3 &#62; Cadastro de Produtos_3","Identificação do Item  Código do Produto = 60 caracteres máximo Nome = 120 caracteres máximo Tipo = definir conforme;  -Produtos = Todos...",""],
["cadastro_de_usuarios.html","Guia de Orientações e Treinamentos  &#62; Configurações Básicas  &#62; Cadastro de Usuarios","Enter topic text here.",""],
["cadastro_estabelecimento.html","Guia de Orientações e Treinamentos  &#62; Configurações Básicas  &#62; Cadastro de Empresas &#62; Estabelecimento &#62; Cadastro Estabelecimento","Campos Obrigatórios para NFe e Sped  Razão Social - informar a razão social do emitente CNPJ - informar o CNPJ do emitente, sem formatação ou...",""],
["cadastro_produtos.html","Guia de Orientações e Treinamentos  &#62; Módulo Cadastros &#62; Visão Geral de todos os Cadastros &#62; Cadastro de Produtos &#62; Cadastro Produtos","O Cadastro de Artigos registra todas as informações e configurações de todos os PRODUTOS que a Empresa comercializa. Neste cadastro é possível reg...",""],
["cadastro_produtos2.html","Guia de Orientações e Treinamentos  &#62; Módulo Cadastros &#62; Visão Geral de todos os Cadastros &#62; Cadastro de Produtos &#62; Cadastro Produtos &#62; Cadastro Produtos","O Cadastro de produto é uma das vigas mestras do Empresa, pois ele trata de informações que geralmente tem um peso muito grande em qualquer empres...",""],
["cadastro_produtos2_2.html","Guia de Orientações e Treinamentos  &#62; Módulo Relatórios &#62; Visão Geral de todos os Cadastros_2 &#62; Cadastro de Produtos_2 &#62; Cadastro Produtos_2 &#62; Cadastro Produtos_2","O Cadastro de produto é uma das vigas mestras do Empresa, pois ele trata de informações que geralmente tem um peso muito grande em qualquer empres...",""],
["cadastro_produtos2_3.html","Guia de Orientações e Treinamentos  &#62; Módulo Bancario &#62; Visão Geral de todos os Cadastros_3 &#62; Cadastro de Produtos_3 &#62; Cadastro Produtos_3 &#62; Cadastro Produtos_3","O Cadastro de produto é uma das vigas mestras do Empresa, pois ele trata de informações que geralmente tem um peso muito grande em qualquer empres...",""],
["cadastro_produtos_2.html","Guia de Orientações e Treinamentos  &#62; Módulo Relatórios &#62; Visão Geral de todos os Cadastros_2 &#62; Cadastro de Produtos_2 &#62; Cadastro Produtos_2","O Cadastro de Artigos registra todas as informações e configurações de todos os PRODUTOS que a Empresa comercializa. Neste cadastro é possível reg...",""],
["cadastro_produtos_3.html","Guia de Orientações e Treinamentos  &#62; Módulo Bancario &#62; Visão Geral de todos os Cadastros_3 &#62; Cadastro de Produtos_3 &#62; Cadastro Produtos_3","O Cadastro de Artigos registra todas as informações e configurações de todos os PRODUTOS que a Empresa comercializa. Neste cadastro é possível reg...",""],
["cadastro_transportadora.html","Guia de Orientações e Treinamentos  &#62; Módulo Cadastros &#62; Visão Geral de todos os Cadastros &#62; Cadastro Transportadora","Nome - informar a razão social do transportador CNPJ/CPF - informar o CNPJ/CPF do transportador, sem formatação ou máscara IE - informar a IE do t...",""],
["cadastro_transportadora_2.html","Guia de Orientações e Treinamentos  &#62; Módulo Relatórios &#62; Visão Geral de todos os Cadastros_2 &#62; Cadastro Transportadora_2","Nome - informar a razão social do transportador CNPJ/CPF - informar o CNPJ/CPF do transportador, sem formatação ou máscara IE - informar a IE do t...",""],
["cadastro_transportadora_3.html","Guia de Orientações e Treinamentos  &#62; Módulo Bancario &#62; Visão Geral de todos os Cadastros_3 &#62; Cadastro Transportadora_3","Nome - informar a razão social do transportador CNPJ/CPF - informar o CNPJ/CPF do transportador, sem formatação ou máscara IE - informar a IE do t...",""],
["cadeia_do_ws.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Procedimentos Instalação NF-e 2G 2 &#62; Certificados &#62; Cadeia do WS","Instalação do Certificado Digital da Cadeia do WS  Além do certificado digital do cliente, também é necessário instalar os certificados digit...",""],
["calculo_nfe_importacao.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Calculo NFe Importação","EMISSÃO DE NOTA FISCAL DE ENTRADA DE IMPORTAÇÃO:   1. O valor das mercadorias será compreendido pela soma de: CIF + Impostos de Importaç...",""],
["cancelamento_de_nfe.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Cancelamento, Denegação, Inutilização e CCe","Após ter o seu uso autorizado pela SEFAZ, uma NF-e não poderá sofrer qualquer alteração, pois qualquer modificação no seu conteúdo invalida a sua ...",""],
["cancelar.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Cancelamento, Denegação, Inutilização e CCe &#62; Cancelar","Finalidade  Caso tenha havido algum erro de preenchimento na NF-e, e que só tenha sido detectado após a mesma ter sido AUTORIZADA, será &#38;nbsp...",""],
["carta_de_correcao.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Cancelamento, Denegação, Inutilização e CCe &#62; Carta de Correção (CCe)","Descrição:  Funcionalidade para Cancelamento de NF-e.  Os principais parâmetros da carta de correção são:      chave de a...",""],
["cartoesdecrdito.html","Guia de Orientações e Treinamentos  &#62; Módulo Impostos &#62; Sped 2 &#62; Visita 1 &#62; Cadastros &#62; Cartoes de Crédito","Ir Para: Cadastros\\Cartões de Crédito:   1.Dados dos Participantes (Cartões de Crédito) 1.1.  Nome 1.2.   Se Pessoa Jurídica: CNPJ;...",""],
["certificados.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Procedimentos Instalação NF-e 2G 2 &#62; Certificados","O projeto da NF-e utiliza certificados digitais para autenticação de acesso e assinatura digital.",""],
["certificado_a3.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Procedimentos Instalação NF-e 2G 2 &#62; Certificados &#62; Instalação Certificado &#62; Certificado A3","Passo: Sistemas Homologados O Windows Vista e o navegador Internet Explore 8.0, possui diretrizes de segurança específicas que modificam o fluxo p...",""],
["certificado_por_email.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Procedimentos Instalação NF-e 2G 2 &#62; Certificados &#62; Instalação Certificado &#62; Certificado por email","Instalando o Certificado Digital Depois de concluída a compra do certificado, você deverá receber um e-mail para a emissão do certificado digital....",""],
["clientesefornecedores.html","Guia de Orientações e Treinamentos  &#62; Módulo Impostos &#62; Sped 2 &#62; Visita 1 &#62; Cadastros &#62; Clientes e Fornecedores","Ir Para: Cadastros\\Fabricante e Fornecedor:   1.Dados dos Participantes (Fabricantes e Fornecedores) 1.   Nome 2.   Se Pessoa Juríd...",""],
["codigo_de_barras_lote_grade.html","Guia de Orientações e Treinamentos  &#62; Módulo Especiais &#62; Codigo de Barras Lote/Grade","Configuração para código barra  Produtos sem grade: Rotina – Especiais &#62; Geração de código Barras: Parâmetros de estabelecimento &#62; Padr...",""],
["complementar.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Complementar Imposto","Uma NF-e autorizada pela SEFAZ não pode ser mais modificada, mesmo que seja para correção de erros de preenchimento. Ressalte-se que a NF-e tem ex...",""],
["complementar_cadastro_tipo.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Complementar Imposto &#62; Complementar Cadastro Tipo","Classe do tipo = Complemento de Imposto Nota Eletrônica = Sim Modelo de Nota (Saída) = Selecione o modelo já cadastrado CFOP Venda = ITEM , pois i...",""],
["complementar_imposto_destacad2.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Complementar Imposto &#62; Complementar IMPOSTO DESTACADO A MAIOR","4.3 – VALOR DO IMPOSTO DESTACADO A MAIOR  Deverá o destinatário no momento da entrada das mercadorias, examinar se o documento fiscal foi cor...",""],
["complementar_imposto_destacado.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Complementar Imposto &#62; Complementar IMPOSTO DESTACADO A MENOR","VALOR DO IMPOSTO DESTACADO A MENOR  a) – Regularização dentro do período de apuração.  Nesta hipótese, a correção será feita mediante si...",""],
["complementar_preenchimento.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Complementar Imposto &#62; Complementar IMPOSTO DESTACADO A MENOR &#62; Complementar Preenchimento","Dados do Destinatário/Remetente Deverá constar como destinatário, o nome, o endereço e os números de inscrição estadual e no Cadastro Nacional de ...",""],
["complementar_regras.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Complementar Imposto &#62; Complementar IMPOSTO DESTACADO A MENOR &#62; Complemento ICMS","NF-e de Complemento de ICMS A NF-e de complemento de ICMS é emitida para complementar o ICMS destacado a menor, uma NF-e complementar só pode refe...",""],
["configuracao_boleto_bancario.html","Guia de Orientações e Treinamentos  &#62; Módulo Especiais &#62; Configuração Boleto Bancario","Enter topic text here.",""],
["configuracoesbasicas.html","Guia de Orientações e Treinamentos  &#62; Configurações Básicas ","Enter topic text here.",""],
["configuracoesnfehc.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Procedimentos Instalação NF-e 2G 2 &#62; Instalação NFe &#62; Arquivo Conttroller_NF-e","Arquivo Conttroller_NF-e.ini C:\\CONTTROLLER\\Notaeletronica\\Conttroller_NFe.ini",""],
["configura_active_x.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Procedimentos Instalação NF-e 2G 2 &#62; Certificados &#62; Configura Active X","passo: Configuração ActiveX  Abra uma página (qualquer) da Internet. Clique na opção &#8220;Ferramentas&#8221; no topo da página e depois em &#8220;Opções da I...",""],
["conhecendo_os_botoes_e_navegab.html","Guia de Orientações e Treinamentos  &#62; Visão Geral &#62; Conhecendo os Botões e navegabilidade do sistema","/* */ Guia de Orientações e Treinamentos Visão Geral Conhecendo os Botões e navegabilidade do sistema Navigation: Guia de Orientações e Treinament...",""],
["conhecendo_os_modulos.html","Conhecendo os Módulos","Enter topic text here.",""],
["consignacao.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Tipos de Entrada / saida &#62; Consignação","CONSIGNAÇÃO MERCANTIL  Na consignação mercantil existe uma relação entre dois contribuintes, em que um é o titular das mercadorias e o outro ...",""],
["consulta_nfe_no_sefaz.html","Faq &#62; Consulta NFe no Sefaz","O módulo de acesso contribuintes às informações da NF-e? ",""],
["consulta_relatorios.html","Guia de Orientações e Treinamentos  &#62; Módulo Compras &#62; Consulta Relatórios","Enter topic text here.",""],
["consulta_relatorios2.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; Consulta Relatórios","Enter topic text here.",""],
["consulta_relatorios3.html","Guia de Orientações e Treinamentos  &#62; Módulo Financeiro &#62; Consulta Relatórios","Enter topic text here.",""],
["contabilista.html","Guia de Orientações e Treinamentos  &#62; Módulo Impostos &#62; Sped 2 &#62; Visita 1 &#62; Cadastros &#62; Contabilista","Ir Para: Cadastros\\Gerais\\Estabelecimento:  1.- Fiscal: 1.1.- INFORMAÇÕES PARA o SPED 1.1.1.Perfil Da Empresa (A/B/C): Perfil do Contribuinte...",""],
["contigencia.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Contingência","Quando não for possível a transmissão das informações referentes à nota fiscal emitida, será utilizado o DANFE em contingência. ",""],
["contigencia_depc.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Contingência &#62; Contingência DEPC","Transmitir Declaração Prévia de Emissão em Contingência - DPEC (NF-e), com base em leiaute estabelecido no Ato COTEPE nº 34/08 para a Receita Fede...",""],
["contigencia_fs-da.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Contingência &#62; Contingência FS-DA","Imprimir o DANFE em Formulário de Segurança para Impressão de Documento Auxiliar de Documento Fiscal Eletrônico (FS-DA), em no mínimo duas vias, c...",""],
["contigencia_scan.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Contingência &#62; Contingência SCAN","Transmitir o arquivo digital da NF-e para o Sistema de Contingência do Ambiente Nacional (SCAN) - Receita Federal do Brasil, no qual a Receita Fed...",""],
["controle_paciente__medico_e_co.html","Guia de Orientações e Treinamentos  &#62; Módulo Especiais &#62; Controle Paciente, Medico e Convenios","Rotina controle Paciente, Médico e Convênio. Configura Parâmetro Estabelecimento&#62;&#62; Diversos&#62;&#62; Medicamento e Mat. Hospitalar = Sim &#38;nbs...",""],
["convencoes_utilizadas.html","Guia de Orientações e Treinamentos  &#62; Introdução &#62; Convenções Utilizadas","Com o objetivo de tornar a leitura deste manual mais clara, adotamos algumas convenções de nomenclatura e tipográficas, relacionadas a seguir:",""],
["copia_chave_.html","Faq &#62; Consulta NFe no Sefaz &#62; Copia Chave","CTRL + C  ,  A chave é copiada para Área de Transferencia do WIN permitido assim colar como um texto em qualquer aplicativo.",""],
["corrigidovisualizacaododanfe.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Rotinas de Manutenção &#62; Corrigindo Visualização do DANFE","Fechar o Gerenciado de NF-e; Gerar NOVO arquivo NF-e no HC; Alterar o nome do arquivo txt  para o nome da chave gerada  EX.:  H_S_0...",""],
["cotacao.html","Guia de Orientações e Treinamentos  &#62; Módulo Compras &#62; Cotação","COTAÇÃO    Disponível a partir da versão 2012.05.23.X O conceito adotado para Cotação em economia consiste no ato ou efeito de cotar, es...",""],
["cotacao_parametrizacao.html","Guia de Orientações e Treinamentos  &#62; Módulo Compras &#62; Cotação &#62; Cotação Parametrização","1. Liberando a tela de Cotação nova O usuário deverá inserir o seguinte parâmetro interno = COTACAO_NOVA com valor igual &#39;Sim&#39; na tabela PARAMETRO...",""],
["criacao_de_relatorios.html","Guia de Orientações e Treinamentos  &#62; Módulo Relatórios &#62; Criação de Relatórios","Enter topic text here.",""],
["crt.html","Guia de Orientações e Treinamentos  &#62; Módulo Impostos &#62; Regime Tributário Estabelecimento &#62; Parametros Estabelecimento &#62; Impostos","1- Regime Tributário - Código de Regime Tributário - CRT, valores válidos: (campo Obrigatório).",""],
["csosn_x_cst.html","Faq &#62; CSOSN x CST","Aplicação com operações de saída /entrada  TABELA DE CORRELAÇÃO CST X CSOSN-CRT  EMPRESA SIMPLES NACIONAL COMPRANDO DE UMA EMPRESA DO SI...",""],
["dados_complemmentares.html","Guia de Orientações e Treinamentos  &#62; Visão Geral &#62; Cadastros &#62; Cadastros de Clientes/Fornecedores &#62; Cobrança , SPC e Outros","Os Principais campos desta página: Endereço para Cobrança. O endereço para cobrança tem os mesmos campos que tem o endereço para Faturamento. &#38;nbs...",""],
["daruma_framework.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; Instalação ECF &#62; Modelo Daruma &#62; Daruma Framework","Observações:  1. O XML não é um arquivo de configuração como o registro, ele é somente uma base de informações baseadas no conteúdo do regist...",""],
["declaracao_de_icms.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Complementar Imposto &#62; Complementar IMPOSTO DESTACADO A MAIOR &#62; Modelos de Declaração &#62; DECLARAÇÃO DE ICMS","DECLARAÇÃO DE NÃO-APROVEITAMENTO DE ICMS  Toda vez que a empresa fornecedora destacar ICMS a maior, o destinatário deverá apropriar-se soment...",""],
["declaracao_de_ipi.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Complementar Imposto &#62; Complementar IMPOSTO DESTACADO A MAIOR &#62; Modelos de Declaração &#62; DECLARAÇÃO DE IPI","DECLARAÇÃO DE NÃO - APROVEITAMENTO DE IPI  Toda vez que a empresa fornecedora destacar ICMS a maior, o destinatário deverá apropriar-se somen...",""],
["denegada.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Cancelamento, Denegação, Inutilização e CCe &#62; Denegada","Denegação da Autorização de Uso da NF-e, em virtude:",""],
["di.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Calculo NFe Importação &#62; NF Importação &#62; DI","Documento eletrônico que consolida as informações cambiais, tributárias, fiscais, comerciais e estatísticas de uma operação de importação de bens,...",""],
["dll_capicom.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Procedimentos Instalação NF-e 2G 2 &#62; Certificados &#62; DLL Capicom","CAPICOM é uma função de conjunto usado com operações de criptografia de páginas Web e pode ser encontrado no Windows Software Development Kit (SDK...",""],
["emisao_scan.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Contingência &#62; Contingência SCAN &#62; Emissão SCAN","1- Alterar no gerenciador NFe o tipo de produção para MODO SCAN",""],
["estabelecimento.html","Guia de Orientações e Treinamentos  &#62; Configurações Básicas  &#62; Cadastro de Empresas &#62; Estabelecimento","Enter topic text here.",""],
["estabelecimento1.html","Guia de Orientações e Treinamentos  &#62; Módulo Impostos &#62; Sped 2 &#62; Visita 1 &#62; Cadastros &#62; Estabelecimento","Ir Para: Cadastros\\Gerais\\Estabelecimento:                  Genéricos  1Nome Fantasia 2CNPJ 3Ins...",""],
["estabelecimento_2.html","Guia de Orientações e Treinamentos  &#62; Módulo Impostos &#62; Sped 2 &#62; Visita 1 &#62; Parâmetros &#62; Estabelecimento 2","Ir Para: Especiais\\Parâmetro\\Estabelecimento:  1.Parâmetro - Sped 1.1.Dados para acesso Servidor do FlashFiler   1.1.1.Servidor do Flash...",""],
["estacaocaixa2fibs.html","Guia de Orientações e Treinamentos  &#62; Instalação e Abertura do HC  &#62; Instalação HC &#62; Instalação Parametrização FibServer &#62; Estação Caixa - 2 FIBs","5 – CAIXA COM 2 FIBS;  Passo 01: Instalando OU ATUALIZANDO caixa com 2 conttroller_fibserver;  Verificar a versão do Firebird, eliminand...",""],
["estacaofibserveratalho.html","Guia de Orientações e Treinamentos  &#62; Instalação e Abertura do HC  &#62; Instalação HC &#62; Instalação Parametrização FibServer &#62; Estação FIBSERVER ATALHO","3 – CONFIGURAÇÃO BARRA FIBLOCAL ATALHO (ESTAÇÃO):  1º ) Compartilhar a pasta CONTTROLLER do Servidor.  Obs.: DE PREFERÊNCIA PERMITIR O C...",""],
["estacaofibserverexecultavellocal.html","Guia de Orientações e Treinamentos  &#62; Instalação e Abertura do HC  &#62; Instalação HC &#62; Instalação Parametrização FibServer &#62; Estação FIBSERVER EXECUTAVEL - LOCAL","2 – CONFIGURAÇÃO Conttroller_FIBServer LOCAL EXECUTÁVEL (ESTAÇÃO);",""],
["estao.html","Guia de Orientações e Treinamentos  &#62; Módulo Impostos &#62; Sped 2 &#62; Visita 1 &#62; Parâmetros &#62; Estação","Ir Para: Especiais\\Parâmetro\\Estação de Trabalho:  1.Configuração da Estação ECF 1.1.Modelo – Informar o Modelo da ECF. 1.2.Número serial ECF...",""],
["estruturaepastas.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Procedimentos Instalação NF-e 2G 2 &#62; Instalação NFe &#62; Estrutura e Pastas","Configurar a maquina com um mapeamento comum entre todas as maquina do faturamento para o sistema High-Commerce ou Gestor coloque os txt gerados p...",""],
["estrutura_deste_manual.html","Guia de Orientações e Treinamentos  &#62; Introdução &#62; Estrutura Deste Manual","Este manual foi organizado numa sequência parecida com a do menu principal do sistema, inicia com uma página de abertura e conclui com as ferramen...",""],
["exclucao_log_.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Rotinas de Manutenção &#62; Exclusão Log Duplicados ","/* */ Guia de Orientações e Treinamentos Módulo Vendas NF_e 2G - Nota Fiscal Eletrônica Rotinas de Manutenção Exclusão Log Duplicados Navigation: ...",""],
["exercicios_propostos_-_compras.html","Guia de Orientações e Treinamentos  &#62; Módulo Compras &#62; Exercicios Propostos - Compras","Enter topic text here.",""],
["exercicios_propostos_-_faturam.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; Exercícios Propostos - Faturamento","Enter topic text here.",""],
["exercicios_propostos_-_finance.html","Guia de Orientações e Treinamentos  &#62; Módulo Financeiro &#62; Exercícios Propostos - Financeiro","Enter topic text here.",""],
["exportar_relatorios.html","Guia de Orientações e Treinamentos  &#62; Módulo Diversos &#62; Exportar Relatórios","Enter topic text here.",""],
["facs.html","Faq","Erro : 041 Classe : 041A CDSMemo : Cannot perform this operation on an open dataset",""],
["falha_registro_dll.html","Faq &#62; Faq DLL &#62; Falha registro DLL","As principais causas de falha no registo da DLL são:",""],
["faq-_di.html","Faq &#62; FAQ - DI","Enter topic text here.",""],
["faq.html","Faq &#62; FAQ","Enter topic text here.",""],
["faq_-_assinar.html","Faq &#62; FAX - Assinatura Digital &#62; FAQ - Assinar","Assinatura Digital XML no padrão do Projeto NF-e  Descrição: Funcionalidade para realizar a assinatura digital no padrão XML Digital Signatur...",""],
["faq_-_assinatura_digital.html","Faq &#62; FAX - Assinatura Digital","O usuário da NF-e pode enfrentar problemas com a assinaturas digital em momentos distintos do processo:",""],
["faq_-_cancelar.html","Faq &#62; FAQ - CANCELAR","O resultado da chamada do Cancela NFe é a mensagem XML composta pelo pedido de cancelamento e respectivo protocolo de homologação do cancelamento ...",""],
["faq_-_carta_de_correcao.html","Faq &#62; FAQ - Carta de Correção","Quando podemos emitir a CC-e?  A CC-e pode ser emitida para \"corrigir\" alguns erros de preenchimento da Nota Fiscal eletrônica. &#38;nb...",""],
["faq_-_compartilhamento_pasta.html","Faq &#62; FAQ - Compartilhamento Pasta","/* */ Faq FAQ - Compartilhamento Pasta Navigation: Faq FAQ - Compartilhamento Pasta ",""],
["faq_-_inutilizacao.html","Faq &#62; FAQ - Inutilização","O resultado da chamada do InutilizaNroNF é a mensagem XML composta pelo pedido de inutilização e respectivo protocolo de homologação de inutilizaç...",""],
["faq_dll.html","Faq &#62; Faq DLL","O uso da DLL requer a sua instalação que consiste no registro da DLL no registra do Windows.",""],
["formularios_de_seguranca.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Contingência &#62; Contingência FS-DA &#62; Formulários de Segurança","Atualmente existem os seguintes tipos de formulários de segurança:",""],
["geracao_arquivos_paf.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; Instalação ECF &#62; Geração Arquivos DAT","Geração Arquivos DAT    Deve ser gerado arquivo Conttroller.dat que ira conter os dados da ECF.O arquivo .dat será gerado a parti de inf...",""],
["geracao_arquivos_tef.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; Instalação ECF &#62; Geração Arquivos TEF","Geração Arquivos TEF    1. Configura arquivo &#8220;tefconfig_v3.xml&#8221; 1.1. Copiar arquivo para pasta Conttroller/Sistema 1.2. Alterar linha on...",""],
["gtin.html","Faq &#62; FAQ - GTIN","Enter topic text here.  1. O que é o GTIN ? GTIN, acrônimo para Global Trade Item Number é um identificador para itens comerciais desenvolvid...",""],
["guiadeorientacoestreinamentos.html","Guia de Orientações e Treinamentos ","GUIA DE ORIENTAÇÕES E TREINAMENTOS",""],
["guia_treinamento_content.html","Guia de Orientações e Treiamnetos","Guia de Orientações e Treinamentos Introdução Convenções Utilizadas Estrutura Deste Manual Visão Geral Menu Principal Cadastros Cadastros Gerais C...",""],
["guia_treinamento_ftsearch.html","Guia de Orientações e Treiamnetos","Entre uma ou mais palavras-chave para pesquisar (&#39;*&#39; e curingas são suportados &#39;?&#39;): Você precisa ter o JavaScript habilitado para usar esta versã...",""],
["ibexpert.html","Guia de Orientações e Treinamentos  &#62; Instalação e Abertura do HC  &#62; IBExpert","Instalar o IB-Expert.  Criar uma conexão com o D:\\CONTTROLLER\\Notaeletronica\\banco\\NFELETRONICA.FDB. * Abrir o banco para testar conexão &#38;nbs...",""],
["identificacao_cliente.html","Guia de Orientações e Treinamentos  &#62; Visão Geral &#62; Cadastros &#62; Cadastros de Clientes/Fornecedores &#62; Identificação Cliente","Identificação do Cadastral: A linha superior da tela de edição do cadastro de cliente é usada para identificar o cliente, possui os seguintes camp...",""],
["identificacao_da_nf-e_2g.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Tipos de Entrada / saida &#62; Terminal de Vendas NF-e 2G","CAMPOS OBRIGATÓRIOS:  Série - informar a série do Documento Fiscal, informar 0 (zero) para série única. A emissão normal pode utilizar série ...",""],
["imposto_importacao.html","Guia de Orientações e Treinamentos  &#62; Módulo Cadastros &#62; Visão Geral de todos os Cadastros &#62; Cadastro de Produtos &#62; Imposto Importação","1- Imposto de Importação - Funcionalidade para gerar as informações do II (Imposto de Importação) do item na NF-e. Este grupo só precisa ser infor...",""],
["imposto_importacao_2.html","Guia de Orientações e Treinamentos  &#62; Módulo Relatórios &#62; Visão Geral de todos os Cadastros_2 &#62; Cadastro de Produtos_2 &#62; Imposto Importação_2","1- Imposto de Importação - Funcionalidade para gerar as informações do II (Imposto de Importação) do item na NF-e. Este grupo só precisa ser infor...",""],
["imposto_importacao_3.html","Guia de Orientações e Treinamentos  &#62; Módulo Bancario &#62; Visão Geral de todos os Cadastros_3 &#62; Cadastro de Produtos_3 &#62; Imposto Importação_3","1- Imposto de Importação - Funcionalidade para gerar as informações do II (Imposto de Importação) do item na NF-e. Este grupo só precisa ser infor...",""],
["instalacaoeaberturadohc.html","Guia de Orientações e Treinamentos  &#62; Instalação e Abertura do HC ","Enter topic text here.",""],
["instalacaofirebird.html","Guia de Orientações e Treinamentos  &#62; Instalação e Abertura do HC  &#62; Instalação Firebird","Instalação para o Firebird 2.5  Antes da instalação É recomendado que você DESINSTALAR todas as versões anteriores do Firebird ou&#38;n...",""],
["instalacaohc.html","Guia de Orientações e Treinamentos  &#62; Instalação e Abertura do HC  &#62; Instalação HC","Instalar o High-Commerce Executar o arquivo de instalação  No diretório escolhido (c, d, e .etc) execute o arquivo de instalação  Durant...",""],
["instalacaonfe.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Procedimentos Instalação NF-e 2G 2 &#62; Instalação NFe","O ARQUIVO de instalação esta no nosso servidor T:\\INSTALAR\\NotaEletronica_2G",""],
["instalacaoparametrizacaofibserver.html","Guia de Orientações e Treinamentos  &#62; Instalação e Abertura do HC  &#62; Instalação HC &#62; Instalação Parametrização FibServer","Configuração do Conttroller_FIBServer (SERVIDOR E CAIXAS)",""],
["instalacao_certificado.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Procedimentos Instalação NF-e 2G 2 &#62; Certificados &#62; Instalação Certificado","Instalação do Certificado Digital Cliente  Após a aquisição do certificado digital, o próximo passo é a instalação do mesmo no equipamento qu...",""],
["instalacao_dll.html","Faq &#62; Faq DLL &#62; Instalação DLL","Arquivos necessários para instalação da DLL  A versão mais recente da DLL está disponível na instalação da NFe.  O pacote está compactad...",""],
["instalacao_ecf.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; Instalação ECF","Instalação ECF    Modelo este campo é aberto uma janela relacionando todas as impressoras que o sistema já possui driver de comunicação,...",""],
["instalando_serveclient.html","Guia de Orientações e Treinamentos  &#62; Instalação e Abertura do HC  &#62; Instalação HC &#62; Sincronizador &#62; Instalando ConttrollerSincZEOS (Cliente)","1) Instalando o ConttrollerSincZEOS.exe a) Localização/Estrutura das pastas &#62;&#62; COMPACTA.BAT; DELETA.BAT; DESCOMPACTA.BAT e ConttrollerSincZE...",""],
["instalando_serveclient_2.html","Guia de Orientações e Treinamentos  &#62; Instalação e Abertura do HC  &#62; Instalação HC &#62; Sincronizador 4.7 &#62; Instalando ConttrollerSincZEOS (Cliente) 4.7 ","* LOJA   &#62; Sinronizador = contendo a pasta FTP_Files, Contsinc e Contsinc.conf, (arquivo de configuração do Contsinc), FTPClient...",""],
["instalando_serversinc_exe.html","Guia de Orientações e Treinamentos  &#62; Instalação e Abertura do HC  &#62; Instalação HC &#62; Sincronizador &#62; Instalando ServerSinc (Servidor)","1) Instalando ServerSinc.exe a) Copiar arquivo COMPACTA.BAT; DELETA.BAT; DESCOMPACTA.BAT e ServerSinc.exe para a pasta    b) Configurand...",""],
["instalando_serversinc_exe_2.html","Guia de Orientações e Treinamentos  &#62; Instalação e Abertura do HC  &#62; Instalação HC &#62; Sincronizador 4.7 &#62; Instalando ServerSinc (Servidor) 4.7","1) Instalando ServerSinc.exe a) Copiar arquivo COMPACTA.BAT; DELETA.BAT; DESCOMPACTA.BAT e ServerSinc.exe para a pasta  SERVIDOR   &#62;&#38;...",""],
["instalcao_framework.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Procedimentos Instalação NF-e 2G 2 &#62; Framework","Instalar o framework 2.0 (Encontra se na pasta T:\\INSTALAR\\HIGH-COMMERCE\\Instalação Framework.NET 2.0)",""],
["integracao_contabil.html","Guia de Orientações e Treinamentos  &#62; Módulo Diversos &#62; Integração Contabil","Manual Exportação para Sistema Contábil Pré-requisitos: Caso a contabilidade da empresa só adquirir o sistema contábil depois de a empresa adquiri...",""],
["integracao_fiscal.html","Guia de Orientações e Treinamentos  &#62; Módulo Diversos &#62; Integração Fiscal","Enter topic text here.",""],
["introducao.html","Guia de Orientações e Treinamentos  &#62; Introdução","O objetivo principal deste manual é ser um guia para o técnico das soluções Conttroller, tais como: o Hight-Commerce, Pedido Simplificado, Automaç...",""],
["introduction_2.html","Guia de Orientações e Treinamentos  &#62; Módulo Especiais &#62; Configuração para Fabricação Própria 2","Esta é uma operação que só tem sentido para empresas que possuem produção própria, pois ela efetua a transferência dos saldos dos produtos finaliz...",""],
["introduo.html","Guia de Orientações e Treinamentos  &#62; Módulo Impostos &#62; Sped 2 &#62; Introdução","Foi desenvolvida no High-Commerce uma nova opção de importação dos arquivos XML (NFe) de entrada e saídas, e arquivos ECFs (Cupons Fiscais), atrav...",""],
["inutilizacao.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Cancelamento, Denegação, Inutilização e CCe &#62; Inutilização","Inutilização de numeração de NF-e. (Fig.01)  Esta funcionalidade serve para inutilizar um número ou faixa de numeração de NF-e que não foi ut...",""],
["local_de_entrega.html","Guia de Orientações e Treinamentos  &#62; Módulo Cadastros &#62; Visão Geral de todos os Cadastros &#62; Cadastro de Clientes/Fornecedor &#62; Local de Entrega","Este grupo de informação só deve ser informado nos casos em que o local de entrega seja diferente do endereço do destinatário, cabendo ressaltar q...",""],
["local_de_entrega2.html","Guia de Orientações e Treinamentos  &#62; Módulo Cadastros &#62; Visão Geral de todos os Cadastros &#62; Cadastro de Clientes/Fornecedor &#62; Local de Entrega","End. Entrega na NF  Sim = Será utilizado o endereço de entrega  Sim e aplicar tributação da UF de entrega = Será utilizado o endereço de...",""],
["local_de_entrega2_2.html","Guia de Orientações e Treinamentos  &#62; Módulo Relatórios &#62; Visão Geral de todos os Cadastros_2 &#62; Cadastro de Clientes/Fornecedor_2 &#62; Local de Entrega_2","End. Entrega na NF  Sim = Será utilizado o endereço de entrega  Sim e aplicar tributação da UF de entrega = Será utilizado o endereço de...",""],
["local_de_entrega2_3.html","Guia de Orientações e Treinamentos  &#62; Módulo Bancario &#62; Visão Geral de todos os Cadastros_3 &#62; Cadastro de Clientes/Fornecedor_3 &#62; Local de Entrega_3","End. Entrega na NF  Sim = Será utilizado o endereço de entrega  Sim e aplicar tributação da UF de entrega = Será utilizado o endereço de...",""],
["local_de_entrega_2.html","Guia de Orientações e Treinamentos  &#62; Módulo Relatórios &#62; Visão Geral de todos os Cadastros_2 &#62; Cadastro de Clientes/Fornecedor_2 &#62; Local de Entrega_2","Este grupo de informação só deve ser informado nos casos em que o local de entrega seja diferente do endereço do destinatário, cabendo ressaltar q...",""],
["local_de_entrega_3.html","Guia de Orientações e Treinamentos  &#62; Módulo Bancario &#62; Visão Geral de todos os Cadastros_3 &#62; Cadastro de Clientes/Fornecedor_3 &#62; Local de Entrega_3","Este grupo de informação só deve ser informado nos casos em que o local de entrega seja diferente do endereço do destinatário, cabendo ressaltar q...",""],
["lotesegrades.html","Guia de Orientações e Treinamentos  &#62; Módulo Cadastros &#62; Visão Geral de todos os Cadastros &#62; Cadastro de Produtos &#62; LOTES e GRADES","1- Diferença entre LOTE x GRADE para o sistema HC.",""],
["lotesegrades_2.html","Guia de Orientações e Treinamentos  &#62; Módulo Relatórios &#62; Visão Geral de todos os Cadastros_2 &#62; Cadastro de Produtos_2 &#62; LOTES e GRADES_2","1- Diferença entre LOTE x GRADE para o sistema HC.",""],
["lotesegrades_3.html","Guia de Orientações e Treinamentos  &#62; Módulo Bancario &#62; Visão Geral de todos os Cadastros_3 &#62; Cadastro de Produtos_3 &#62; LOTES e GRADES_3","1- Diferença entre LOTE x GRADE para o sistema HC.",""],
["medicamento.html","Guia de Orientações e Treinamentos  &#62; Módulo Cadastros &#62; Visão Geral de todos os Cadastros &#62; Cadastro de Produtos &#62; LOTES e GRADES &#62; Medicamento","Visualizado LOTE medicamento no DANFE    Gerenciador do NFe marca opção Formato do DANFE =  Paisagem",""],
["medicamentos2.html","Guia de Orientações e Treinamentos  &#62; Módulo Cadastros &#62; Visão Geral de todos os Cadastros &#62; Cadastro de Produtos &#62; LOTES e GRADES &#62; Medicamentos","Os medicamentos e as matérias-primas (insumos) farmacêuticas são produtos sujeitos ao regime de vigilância sanitária e, portanto são controlados p...",""],
["medicamentos2_2.html","Guia de Orientações e Treinamentos  &#62; Módulo Relatórios &#62; Visão Geral de todos os Cadastros_2 &#62; Cadastro de Produtos_2 &#62; LOTES e GRADES_2 &#62; Medicamentos_2","Os medicamentos e as matérias-primas (insumos) farmacêuticas são produtos sujeitos ao regime de vigilância sanitária e, portanto são controlados p...",""],
["medicamentos2_3.html","Guia de Orientações e Treinamentos  &#62; Módulo Bancario &#62; Visão Geral de todos os Cadastros_3 &#62; Cadastro de Produtos_3 &#62; LOTES e GRADES_3 &#62; Medicamentos_3","Os medicamentos e as matérias-primas (insumos) farmacêuticas são produtos sujeitos ao regime de vigilância sanitária e, portanto são controlados p...",""],
["medicamento_2.html","Guia de Orientações e Treinamentos  &#62; Módulo Relatórios &#62; Visão Geral de todos os Cadastros_2 &#62; Cadastro de Produtos_2 &#62; LOTES e GRADES_2 &#62; Medicamento_2","Visualizado LOTE medicamento no DANFE    Gerenciador do NFe marca opção Formato do DANFE =  Paisagem",""],
["medicamento_3.html","Guia de Orientações e Treinamentos  &#62; Módulo Bancario &#62; Visão Geral de todos os Cadastros_3 &#62; Cadastro de Produtos_3 &#62; LOTES e GRADES_3 &#62; Medicamento_3","Visualizado LOTE medicamento no DANFE    Gerenciador do NFe marca opção Formato do DANFE =  Paisagem",""],
["menu_cadastros.html","Guia de Orientações e Treinamentos  &#62; Menu Cadastros","Enter topic text here.",""],
["menu_principal.html","Guia de Orientações e Treinamentos  &#62; Visão Geral &#62; Menu Principal","Basicamente, foram usados dois tipos de menus: um que é apresentado na horizontal e permanece fixo na parte superior do vídeo, figura 1, usado com...",""],
["modelos_de_declaracao.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Complementar Imposto &#62; Complementar IMPOSTO DESTACADO A MAIOR &#62; Modelos de Declaração","Enter topic text here.",""],
["modelo_bematech.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; Instalação ECF &#62; Modelo Bematech","Modelo Bematech     Bematech =&#62; TAMBEM funciona para PAF  BematechMFD =&#62; Deve ser configurado para impressoras termicas: &#38;nbs...",""],
["modelo_daruma.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; Instalação ECF &#62; Modelo Daruma","Modelo Daruma    O driver (DLL) é único, ou seja, um Framework, que pode ser utilizado em qualquer um dos produtos Fiscais ou não-fiscai...",""],
["modelo_epson.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; Instalação ECF &#62; Modelo Epson","Modelo Epson    Foi criada a InterfaceEpson.dll, que facilita a utilização das Impressoras Fiscais Epson. Para utilizar a InterfaceEpson...",""],
["modulo_bancario.html","Guia de Orientações e Treinamentos  &#62; Módulo Bancario","Enter topic text here.",""],
["modulo_cadastros.html","Guia de Orientações e Treinamentos  &#62; Módulo Cadastros","Enter topic text here.",""],
["modulo_compras.html","Guia de Orientações e Treinamentos  &#62; Módulo Compras","Enter topic text here.",""],
["modulo_diversos.html","Guia de Orientações e Treinamentos  &#62; Módulo Diversos","Enter topic text here.",""],
["modulo_especiais.html","Guia de Orientações e Treinamentos  &#62; Módulo Especiais","Enter topic text here.",""],
["modulo_faturamento.html","Guia de Orientações e Treinamentos  &#62; Módulo Faturamento","Enter topic text here.",""],
["modulo_ferramentas.html","Guia de Orientações e Treinamentos  &#62; Módulo Diversos","Enter topic text here.",""],
["modulo_financeiro.html","Guia de Orientações e Treinamentos  &#62; Módulo Financeiro","Enter topic text here.",""],
["modulo_impostos.html","Guia de Orientações e Treinamentos  &#62; Módulo Impostos","Enter topic text here.",""],
["modulo_relatorios.html","Guia de Orientações e Treinamentos  &#62; Módulo Relatórios","Enter topic text here.",""],
["modulo_vendas.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas","Enter topic text here.",""],
["napratica.html","Guia de Orientações e Treinamentos  &#62; Módulo Impostos &#62; Sped 2 &#62; Na Pratica","1.O sistema é instalado no Contador e no Cliente ( e configurado para que o Contador possa acessar o Cliente On-Line), e ambos receberão treinamen...",""],
["ncm.html","Guia de Orientações e Treinamentos  &#62; Módulo Cadastros &#62; Visão Geral de todos os Cadastros &#62; Cadastro de Produtos &#62; NCM","Passa a ser obrigatório informar o NCM para Todos os regimes tributarias:(campo obrigatório).",""],
["ncm_2.html","Guia de Orientações e Treinamentos  &#62; Módulo Relatórios &#62; Visão Geral de todos os Cadastros_2 &#62; Cadastro de Produtos_2 &#62; NCM_2","Passa a ser obrigatório informar o NCM para Todos os regimes tributarias:(campo obrigatório).",""],
["ncm_3.html","Guia de Orientações e Treinamentos  &#62; Módulo Bancario &#62; Visão Geral de todos os Cadastros_3 &#62; Cadastro de Produtos_3 &#62; NCM_3","Passa a ser obrigatório informar o NCM para Todos os regimes tributarias:(campo obrigatório).",""],
["new_topic10.html","Guia de Orientações e Treinamentos  &#62; Módulo Especiais &#62; Configuração para Fabricação Própria 2 &#62; Lançando a produção &#62; Preencher Dados Principal","Cliente&#62;&#62; Informar cliente já cadastrado para esta operação;",""],
["new_topic11.html","Guia de Orientações e Treinamentos  &#62; Módulo Especiais &#62; Configuração para Fabricação Própria 2 &#62; Lançando a produção &#62; Preencher Dados Impostos","Selecione o local de estoque da baixa da material prima",""],
["new_topic12.html","Guia de Orientações e Treinamentos  &#62; Módulo Especiais &#62; Configuração para Fabricação Própria 2 &#62; Lançando a produção &#62; Forma de Pagamento","Selecione a Forma de Pagamento: Sem Financeiro Local para transferencia : Local da Entrada do produto pronto F4 para gravar transferencia",""],
["new_topic2.html","Guia de Orientações e Treinamentos  &#62; Módulo Especiais &#62; Configuração para Fabricação Própria 2 &#62; Cadastro&#62;&#62; Tipos de Entrada/Saída &#62; Nome: Transferência – Entrada","Classe do tipo: Trans. p/Produção Baixar Estoque: CFOP (Sugestão 5.151) Estoque reservado: NÃO Validar estoque: SIM Gerar a Pagar: NÃO Gerar a Rec...",""],
["new_topic4.html","Guia de Orientações e Treinamentos  &#62; Módulo Especiais &#62; Configuração para Fabricação Própria 2 &#62; Cadastro&#62;&#62; Tipos de Entrada/Saída &#62; Nome: Ajuste","Classe do tipo: Ajuste Baixar Estoque: CFOP (Sugestão 5.151) (Importante para validar o estoque da matéria prima) Estoque reservado: NÃO Validar e...",""],
["new_topic5.html","Guia de Orientações e Treinamentos  &#62; Módulo Especiais &#62; Configuração para Fabricação Própria 2 &#62; Parâmetro Estabelecimento&#62;&#62; Saída 2","Vincular o tipos de entrada e saída previamente cadastrados. ",""],
["new_topic6.html","Guia de Orientações e Treinamentos  &#62; Módulo Especiais &#62; Configuração para Fabricação Própria 2 &#62; Cadastro do produto acabados","Para ver uma visão geral da área de Produtos clique no ítem Cadastro de Produto.",""],
["new_topic8.html","Guia de Orientações e Treinamentos  &#62; Módulo Especiais &#62; Configuração para Fabricação Própria 2 &#62; Lançando a produção","Depois de fornecidas todas as informações iniciais para a preparação da digitação da Nota de Produção o sistema abre uma tela para digitação das i...",""],
["new_topic9.html","Guia de Orientações e Treinamentos  &#62; Módulo Especiais &#62; Configuração para Fabricação Própria 2 &#62; Lançando a produção &#62; Selecionar o TIPO","Selecione a opção Transferencias Diversas no menu Vendas/Saídas",""],
["nf_e_2g.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica","Podemos conceituar a Nota Fiscal Eletrônica como sendo um documento de existência apenas digital, emitido e armazenado eletronicamente, com o intu...",""],
["nf_importacao.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Calculo NFe Importação &#62; NF Importação","A NF-e de importação é uma nota fiscal de entrada que deve ser emitida antes da desembaraço de importação para acobertar o transporte da mercadori...",""],
["nome_transferencia__saida.html","Guia de Orientações e Treinamentos  &#62; Módulo Especiais &#62; Configuração para Fabricação Própria 2 &#62; Cadastro&#62;&#62; Tipos de Entrada/Saída &#62; Nome: Transferência – Saída","Classe do tipo: Trans. p/ Produção Baixar Estoque: NÃO Estoque reservado: NÃO Validar estoque: SIM Gerar a Pagar: NÃO Gerar a Receber: NÃO Gerar C...",""],
["nota_eletronica.html","Guia de Orientações e Treinamentos  &#62; Módulo Impostos &#62; Regime Tributário Estabelecimento &#62; Parametros Estabelecimento &#62; Nota Eletrônica","FIG. 1 - Os Campos que estão em destaque de Vermelho são OBRIGATÓRIOS",""],
["objetivo.html","Guia de Orientações e Treinamentos  &#62; Módulo Impostos &#62; Sped 2 &#62; Objetivo","Possibilitar que empresas que NÃO utilizam o High-Commerce possam gerar o Sped Fiscal sem necessidade de trocar de sistema, utilizando o High-Comm...",""],
["paf_ecf.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; Instalação ECF &#62; Configurar Tipos Entrada/Saida","Cadastros Tipos Entradas / Saídas    Configurar os tipos de saídas que serão usados pelo estabelecimento. Para Automação e Pedido Simpli...",""],
["paf_ecf_2.html","Guia de Orientações e Treinamentos  &#62; Módulo Relatórios &#62; Visão Geral de todos os Cadastros_2 &#62; Cadastros Modelos_2 &#62; Configurar Tipos Entrada/Saida_2","Cadastros Tipos Entradas / Saídas    Configurar os tipos de saídas que serão usados pelo estabelecimento. Para Automação e Pedido Simpli...",""],
["paf_ecf_3.html","Guia de Orientações e Treinamentos  &#62; Módulo Bancario &#62; Visão Geral de todos os Cadastros_3 &#62; Cadastros Modelos_3 &#62; Configurar Tipos Entrada/Saida_3","Cadastros Tipos Entradas / Saídas    Configurar os tipos de saídas que serão usados pelo estabelecimento. Para Automação e Pedido Simpli...",""],
["parametrizacao_da_estacao.html","Guia de Orientações e Treinamentos  &#62; Configurações Básicas  &#62; Parametrização da Estação","Enter topic text here.",""],
["parametrizacao_dos_impostos_es.html","Guia de Orientações e Treinamentos  &#62; Configurações Básicas  &#62; Cadastro de Empresas &#62; Estabelecimento &#62; Parametrização dos Impostos Estabelecimento","Enter topic text here.",""],
["parametros.html","Guia de Orientações e Treinamentos  &#62; Módulo Impostos &#62; Regime Tributário Estabelecimento &#62; Parametros Estabelecimento","/* */ Guia de Orientações e Treinamentos Módulo Impostos Regime Tributário Estabelecimento Parâmetros Estabelecimento Navigation: Guia de Orientaç...",""],
["parametros_usuarios.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; Instalação ECF &#62; Parametros Usuarios","Parametros Usuarios    Em parâmetros usuários são configurados todos os direitos e restrições de acesso de cada pessoa que vai usar o si...",""],
["parmetros.html","Guia de Orientações e Treinamentos  &#62; Módulo Impostos &#62; Sped 2 &#62; Visita 1 &#62; Parâmetros","São valores que devem ser ativados durante a implantação do sistema atendendo algumas características específicas.",""],
["planinha_com_calculo_nfe_impor.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Calculo NFe Importação &#62; Planilha com Calculo NFe Importação","/* */ Guia de Orientações e Treinamentos Módulo Vendas NF_e 2G - Nota Fiscal Eletrônica Calculo NFe Importação Planilha com Calculo NFe Importação...",""],
["por_estabelecimento.html","Guia de Orientações e Treinamentos  &#62; Visão Geral &#62; Cadastros &#62; Cadastros de Clientes/Fornecedores &#62; Por Estabelecimento","Status . Diz respeito a situação de crédito do cliente. Selecione entre as opções apresentadas. Já está previamente estabelecido oito opções para ...",""],
["procedimentosinstalacaonf-e2g.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Procedimentos Instalação NF-e 2G 2","Observação Importante:  Essa versão 2.11 só funciona com o High Commerce compilado a partir do dia 15/03/2011.  Até porque, a partir de ...",""],
["processo_de_compras_hc.html","Guia de Orientações e Treinamentos  &#62; Módulo Compras &#62; Processo de Compras HC","Enter topic text here.",""],
["processo_de_controle_financeir.html","Guia de Orientações e Treinamentos  &#62; Módulo Financeiro &#62; Processo de Controle Financeiro","Enter topic text here.",""],
["processo_de_faturamento_hc.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; Processo de Faturamento HC","Enter topic text here.",""],
["produtonotafiscaleletronica.html","Guia de Orientações e Treinamentos  &#62; Módulo Cadastros &#62; Visão Geral de todos os Cadastros &#62; Cadastro de Produtos &#62; Nota Fiscal Eletronica","A regra que deve ter maior impacto para os usuário é a regra que exige o uso do CSOSN no caso do emissor ser optante pelo Simples Nacional (CRT=1).",""],
["produtonotafiscaleletronica_2.html","Guia de Orientações e Treinamentos  &#62; Módulo Relatórios &#62; Visão Geral de todos os Cadastros_2 &#62; Cadastro de Produtos_2 &#62; Nota Fiscal Eletronica_2","A regra que deve ter maior impacto para os usuário é a regra que exige o uso do CSOSN no caso do emissor ser optante pelo Simples Nacional (CRT=1).",""],
["produtonotafiscaleletronica_3.html","Guia de Orientações e Treinamentos  &#62; Módulo Bancario &#62; Visão Geral de todos os Cadastros_3 &#62; Cadastro de Produtos_3 &#62; Nota Fiscal Eletronica_3","A regra que deve ter maior impacto para os usuário é a regra que exige o uso do CSOSN no caso do emissor ser optante pelo Simples Nacional (CRT=1).",""],
["produtos.html","Guia de Orientações e Treinamentos  &#62; Módulo Impostos &#62; Sped 2 &#62; Visita 1 &#62; Cadastros &#62; Produtos","Ir Para: Cadastros\\Produtos   1.Em Identificação do produto preencher: 1.1.Descrição do Item – Campo Nome 1.2.Unidade: Unidade de Medida Util...",""],
["produto_com_fabricacao_propria.html","Guia de Orientações e Treinamentos  &#62; Módulo Cadastros &#62; Visão Geral de todos os Cadastros &#62; Cadastro de Produtos &#62; LOTES e GRADES &#62; Produto com Fabricação Propria","No cadastro do produto aba Gerais habilitar Checkbox &#8220;Fabricação Própria&#8221;",""],
["produto_com_fabricacao_propria_2.html","Guia de Orientações e Treinamentos  &#62; Módulo Relatórios &#62; Visão Geral de todos os Cadastros_2 &#62; Cadastro de Produtos_2 &#62; LOTES e GRADES_2 &#62; Produto com Fabricação Propria_2","No cadastro do produto aba Gerais habilitar Checkbox &#8220;Fabricação Própria&#8221;",""],
["produto_com_fabricacao_propria_3.html","Guia de Orientações e Treinamentos  &#62; Módulo Bancario &#62; Visão Geral de todos os Cadastros_3 &#62; Cadastro de Produtos_3 &#62; LOTES e GRADES_3 &#62; Produto com Fabricação Propria_3","No cadastro do produto aba Gerais habilitar Checkbox &#8220;Fabricação Própria&#8221;",""],
["produto_com_grade.html","Guia de Orientações e Treinamentos  &#62; Módulo Cadastros &#62; Visão Geral de todos os Cadastros &#62; Cadastro de Produtos &#62; LOTES e GRADES &#62; Produto com Grade","Enter topic text here.",""],
["produto_com_grade_2.html","Guia de Orientações e Treinamentos  &#62; Módulo Relatórios &#62; Visão Geral de todos os Cadastros_2 &#62; Cadastro de Produtos_2 &#62; LOTES e GRADES_2 &#62; Produto com Grade_2","Enter topic text here.",""],
["produto_com_grade_3.html","Guia de Orientações e Treinamentos  &#62; Módulo Bancario &#62; Visão Geral de todos os Cadastros_3 &#62; Cadastro de Produtos_3 &#62; LOTES e GRADES_3 &#62; Produto com Grade_3","Enter topic text here.",""],
["produto_com_kit.html","Guia de Orientações e Treinamentos  &#62; Módulo Cadastros &#62; Visão Geral de todos os Cadastros &#62; Cadastro de Produtos &#62; LOTES e GRADES &#62; Produto com Kit","Enter topic text here.",""],
["produto_com_kit_2.html","Guia de Orientações e Treinamentos  &#62; Módulo Relatórios &#62; Visão Geral de todos os Cadastros_2 &#62; Cadastro de Produtos_2 &#62; LOTES e GRADES_2 &#62; Produto com Kit_2","Enter topic text here.",""],
["produto_com_kit_3.html","Guia de Orientações e Treinamentos  &#62; Módulo Bancario &#62; Visão Geral de todos os Cadastros_3 &#62; Cadastro de Produtos_3 &#62; LOTES e GRADES_3 &#62; Produto com Kit_3","Enter topic text here.",""],
["produto_com_lolte.html","Guia de Orientações e Treinamentos  &#62; Módulo Cadastros &#62; Visão Geral de todos os Cadastros &#62; Cadastro de Produtos &#62; LOTES e GRADES &#62; Produto com Lote","Enter topic text here.",""],
["produto_com_lolte_2.html","Guia de Orientações e Treinamentos  &#62; Módulo Relatórios &#62; Visão Geral de todos os Cadastros_2 &#62; Cadastro de Produtos_2 &#62; LOTES e GRADES_2 &#62; Produto com Lote_2","Enter topic text here.",""],
["produto_com_lolte_3.html","Guia de Orientações e Treinamentos  &#62; Módulo Bancario &#62; Visão Geral de todos os Cadastros_3 &#62; Cadastro de Produtos_3 &#62; LOTES e GRADES_3 &#62; Produto com Lote_3","Enter topic text here.",""],
["recalculo_comissao.html","Guia de Orientações e Treinamentos  &#62; Módulo Especiais &#62; Recalculo Comissão","Enter topic text here.",""],
["recriar_xml_distribuicao.html","Faq &#62; Consulta NFe no Sefaz &#62; Recriar XML Distribuição","A NF-e é um XML que deve ser gerado pelo emissor da NF-e com todos as informações que a operação exige.",""],
["rede.html","Guia de Orientações e Treinamentos  &#62; Instalação e Abertura do HC  &#62; Instalação HC &#62; Rede","LAN – LOCAL AREA NETWORK  Nas pastas ...\\Conttoller\\Servidor OU ...\\Windows\\System32 (\\Windows\\SysWoW64 para Windows 64 bits) OU ...\\Windows\\...",""],
["reducao_z.html","Faq &#62; FAQ &#62; Redução Z","Enter topic text here.",""],
["reducao_z_2.html","Faq &#62; Redução Z 2","Enter topic text here.",""],
["reenviar_e-mail_.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Reenviar E-mail Individual","A finalidade desta informação é apenas para constar como remetente na mensagem de e-mail.",""],
["reenviar_e-mail_por_lote.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Reenviar E-mail Individual &#62; Reenviar E-mail por lote","/* */ Guia de Orientações e Treinamentos Módulo Vendas NF_e 2G - Nota Fiscal Eletrônica Reenviar E-mail Individual Reenviar E-mail por lote Naviga...",""],
["regime_tributario_estabelecime.html","Guia de Orientações e Treinamentos  &#62; Módulo Impostos &#62; Regime Tributário Estabelecimento","Enter topic text here.",""],
["registrabase.html","Guia de Orientações e Treinamentos  &#62; Instalação e Abertura do HC  &#62; IBExpert &#62; Registra Base ","Criando e Registrando BD Firebird 2.5 no IBExpert Neste breve artigo veremos como implementar a criação e o registro de uma base de dados Firebird...",""],
["registro_no_windows.html","Faq &#62; Faq DLL &#62; Registro no Windows","Registro da biblioteca no Windows       Pré-requisitos  ambiente Windows 32 bits (Windows XP/Vista/7); framework .NET 2.0 inst...",""],
["rejeicao_nf-e_emitidas_em_cont.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Contingência &#62; Contingência FS-DA &#62; Transmissão das NF-e emitidas em Contingência &#62; Rejeição NF-e emitidas em Contingência","Rejeição de NF-e emitidas em Contingência  Caso ocorra a rejeição de alguma NF-e emitida em contingência, o contribuinte deverá: Gerar novame...",""],
["remocao_framework.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Procedimentos Instalação NF-e 2G 2 &#62; Framework &#62; Remoçao Framework","Este artigo passo a passo descreve como solucionar problemas que podem ocorrer quando você instala o .NET Framework 2.0.",""],
["rotinas_de_manutencao.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Rotinas de Manutenção","1- Atualização Status HC e Gestor 2- Correção Visualização DANFE",""],
["second_topic.html","Guia de Orientações e Treinamentos  &#62; Módulo Especiais &#62; Configuração para Fabricação Própria 2 &#62; Cadastro&#62;&#62; Tipos de Entrada/Saída","Para ver uma visão geral da área de Transferencia clique no ítem Operações Compra e Venda.",""],
["servidor.html","Guia de Orientações e Treinamentos  &#62; Instalação e Abertura do HC  &#62; Instalação HC &#62; Instalação Parametrização FibServer &#62; Servidor","1 – SERVIDOR;   CONFIGURAndo SERVIDOR:  Passo 01: EXECUTANDO o Conttroller_FIBServer    Após executar o Conttroller_FIBServer,...",""],
["servidorcaixaonline.html","Guia de Orientações e Treinamentos  &#62; Instalação e Abertura do HC  &#62; Instalação HC &#62; Instalação Parametrização FibServer &#62; Servidor Caixa - OnLine","4 – CAIXA COM SERVIDOR ON-LINE VIA HAMACHI;  Passo 01: Instalando Caixa;  Verificar a versão do Firebird, eliminando fbclient´s de outra...",""],
["servidor_smtp.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Reenviar E-mail Individual &#62; Servidor SMTP","Servidores POP3 e SMTP de Vários Provedores   1. Provedor UOL (Universo On-Line): POP3: pop.uol.com.br SMTP: smtp.uol.com.br P...",""],
["sincronizador.html","Guia de Orientações e Treinamentos  &#62; Instalação e Abertura do HC  &#62; Instalação HC &#62; Sincronizador","Sincronizador    O PAF-ECF deve, para viabilizar a utilização de Sistema de Gestão (SG) ou de sistema de emissão de documento fiscal por...",""],
["sincronizador_2.html","Guia de Orientações e Treinamentos  &#62; Instalação e Abertura do HC  &#62; Instalação HC &#62; Sincronizador 4.7","Sincronizador     Foi desenvolvida uma nova ferramenta de sincronização que está sendo aplicada em alguns clientes que depende da atuali...",""],
["situacao_tributaria.html","Guia de Orientações e Treinamentos  &#62; Módulo Cadastros &#62; Visão Geral de todos os Cadastros &#62; Cadastro de Produtos &#62; Imposto Importação &#62; Situacao Tributaria","ST ICMS ISENTO OUTROS Reducao SUBSTITUICAO 00 Sim Nao Nao Nao Nao 10 Sim Nao Nao Nao Sim 20 Sim Sim Nao Sim Nao 30 Nao Sim Nao Nao Sim 40 Nao Si",""],
["situacao_tributaria_2.html","Guia de Orientações e Treinamentos  &#62; Módulo Relatórios &#62; Visão Geral de todos os Cadastros_2 &#62; Cadastro de Produtos_2 &#62; Imposto Importação_2 &#62; Situacao Tributaria_2","ST ICMS ISENTO OUTROS Reducao SUBSTITUICAO 00 Sim Nao Nao Nao Nao 10 Sim Nao Nao Nao Sim 20 Sim Sim Nao Sim Nao 30 Nao Sim Nao Nao Sim 40 Nao Si",""],
["situacao_tributaria_3.html","Guia de Orientações e Treinamentos  &#62; Módulo Bancario &#62; Visão Geral de todos os Cadastros_3 &#62; Cadastro de Produtos_3 &#62; Imposto Importação_3 &#62; Situacao Tributaria_3","ST ICMS ISENTO OUTROS Reducao SUBSTITUICAO 00 Sim Nao Nao Nao Nao 10 Sim Nao Nao Nao Sim 20 Sim Sim Nao Sim Nao 30 Nao Sim Nao Nao Sim 40 Nao Si",""],
["sped.html","Guia de Orientações e Treinamentos  &#62; Módulo Cadastros &#62; Visão Geral de todos os Cadastros &#62; Cadastro de Produtos &#62; SPED","Ex. Finalidade Impostos Complementar",""],
["sped_2.html","Guia de Orientações e Treinamentos  &#62; Módulo Impostos &#62; Sped 2","Instituído pelo Decreto nº 6.022, de 22 de janeiro de 2007, o Sistema Público de Escrituração Digital (Sped) faz parte do Programa de Aceleração d...",""],
["sped_3.html","Guia de Orientações e Treinamentos  &#62; Módulo Relatórios &#62; Visão Geral de todos os Cadastros_2 &#62; Cadastro de Produtos_2 &#62; SPED_3","Ex. Finalidade Impostos Complementar",""],
["sped_4.html","Guia de Orientações e Treinamentos  &#62; Módulo Bancario &#62; Visão Geral de todos os Cadastros_3 &#62; Cadastro de Produtos_3 &#62; SPED_4","Ex. Finalidade Impostos Complementar",""],
["tiposdeentradaesada.html","Guia de Orientações e Treinamentos  &#62; Módulo Impostos &#62; Sped 2 &#62; Visita 1 &#62; Parâmetros &#62; Tipos de Entrada e Saída","Ir Para: Especiais\\Parâmetro\\Tipos de Entradas / saídas:",""],
["tipos_de_entrada___saida.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Tipos de Entrada / saida","Enter topic text here.",""],
["transmissao_das_nf-e_emitidas_.html","Guia de Orientações e Treinamentos  &#62; Módulo Vendas &#62; NF_e 2G - Nota Fiscal Eletrônica &#62; Contingência &#62; Contingência FS-DA &#62; Transmissão das NF-e emitidas em Contingência","A emissão de NF-e em contingência é um procedimento de exceção e existem algumas ações que devem ser tomadas após a recuperação da falha, a princi...",""],
["transportadora.html","Guia de Orientações e Treinamentos  &#62; Módulo Cadastros &#62; Visão Geral de todos os Cadastros &#62; Cadastro Transportadora &#62; Transportadora","Funcionalidade para gerar o XML dos dados do Transporte da NF-e",""],
["transportadora_2.html","Guia de Orientações e Treinamentos  &#62; Módulo Impostos &#62; Sped 2 &#62; Visita 1 &#62; Cadastros &#62; Transportadora 2","Ir Para: Cadastros\\Transportadora:  1.Dados dos Participantes (Transportadora) 1.1.   Nome 1.2.   Se Pessoa Jurídica: CNPJ; Se Pess...",""],
["transportadora_3.html","Guia de Orientações e Treinamentos  &#62; Módulo Relatórios &#62; Visão Geral de todos os Cadastros_2 &#62; Cadastro Transportadora_2 &#62; Transportadora_3","Funcionalidade para gerar o XML dos dados do Transporte da NF-e",""],
["transportadora_4.html","Guia de Orientações e Treinamentos  &#62; Módulo Bancario &#62; Visão Geral de todos os Cadastros_3 &#62; Cadastro Transportadora_3 &#62; Transportadora_4","Funcionalidade para gerar o XML dos dados do Transporte da NF-e",""],
["tributacao_produtos___servicos.html","Guia de Orientações e Treinamentos  &#62; Módulo Impostos &#62; Tributação Produtos / Serviços","Enter topic text here.",""],
["usuario.html","Guia de Orientações e Treinamentos  &#62; Módulo Impostos &#62; Sped 2 &#62; Visita 1 &#62; Cadastros &#62; Usuario","Ir Para: Cadastros\\Gerais\\Usuário:   1- Liberar permissão de acesso ao Sistema FISCAL",""],
["usurios.html","Guia de Orientações e Treinamentos  &#62; Módulo Impostos &#62; Sped 2 &#62; Visita 1 &#62; Parâmetros &#62; Usuários","Ir Para: Especiais\\Parâmetro\\Usuários:  1-Liberar acesso a Tela de Seleção de Sistemas     2- Liberar acesso a Tela de Importação XML",""],
["visao_geral.html","Guia de Orientações e Treinamentos  &#62; Visão Geral","O objetivo deste item é dar uma visão geral das soluções Conttroller, quanto às técnicas utilizadas para facilitar a utilização, além de descrever...",""],
["visao_geral_de_todos_os_cadast.html","Guia de Orientações e Treinamentos  &#62; Módulo Cadastros &#62; Visão Geral de todos os Cadastros","É a primeira opção do menu principal e dá acesso aos Cadastros existentes no sistema.",""],
["visao_geral_de_todos_os_cadast_2.html","Guia de Orientações e Treinamentos  &#62; Módulo Relatórios &#62; Visão Geral de todos os Cadastros_2","É a primeira opção do menu principal e dá acesso aos Cadastros existentes no sistema.",""],
["visao_geral_de_todos_os_cadast_3.html","Guia de Orientações e Treinamentos  &#62; Módulo Bancario &#62; Visão Geral de todos os Cadastros_3","É a primeira opção do menu principal e dá acesso aos Cadastros existentes no sistema.",""],
["visita1.html","Guia de Orientações e Treinamentos  &#62; Módulo Impostos &#62; Sped 2 &#62; Visita 1","1.- Servidor: Instalação e Configuração; 2.- Servidor: Liberação das portas e configuração acesso remoto; 3.- Instalação e configuração das estaçõ...",""]];
